
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '6C7F88D84229C779BE5FE6E13C184200'
    
_lr_action_items = {'TAB':([2,9,10,12,14,],[7,11,-5,13,15,]),'.':([5,],[8,]),'INTEGER':([0,7,8,11,13,15,],[5,5,10,5,5,5,]),'LOAD':([0,],[6,]),'$end':([1,3,4,6,10,16,],[-2,0,-1,-3,-5,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'data':([0,],[1,]),'float':([0,7,11,13,15,],[2,9,12,14,16,]),'start':([0,],[3,]),'load':([0,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> load','start',1,'p_start','P5Parser.py',48),
  ('start -> data','start',1,'p_start','P5Parser.py',49),
  ('load -> LOAD','load',1,'p_load','P5Parser.py',53),
  ('data -> float TAB float TAB float TAB float TAB float','data',9,'p_data','P5Parser.py',56),
  ('float -> INTEGER . INTEGER','float',3,'p_float','P5Parser.py',60),
]
